from DoublyLinkedList import DoublyLinkedList

if __name__ == "__main__":
    custom = DoublyLinkedList()
    custom.add(1)
    custom.add(2)
    custom.add(3)
    custom.add(4)
    custom.add(5)
    custom.add(6)
    custom.add(7)
    print(custom)
    #print(custom.count())
    #custom.add_to_first(1)
    #custom.add_at_index(2, 99)
    #custom.add_at_index(4, 98)
    custom.delete(2)
    #custom.pop()
    #print(custom)
    #custom.pop()
    #print(custom)
    #custom.pop()
    #custom.pop()
    print(custom)
    #custom.reverse()
    #print(custom)
